// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: expected_payments.sql

package db

import (
	"context"
	"time"
)

const createExpectedPayment = `-- name: CreateExpectedPayment :one
INSERT INTO expected_payments (
  name,
  amount,
  date,
  month_id
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, name, amount, date, month_id
`

type CreateExpectedPaymentParams struct {
	Name    string    `json:"name"`
	Amount  int32     `json:"amount"`
	Date    time.Time `json:"date"`
	MonthID int64     `json:"month_id"`
}

func (q *Queries) CreateExpectedPayment(ctx context.Context, arg CreateExpectedPaymentParams) (ExpectedPayment, error) {
	row := q.db.QueryRow(ctx, createExpectedPayment,
		arg.Name,
		arg.Amount,
		arg.Date,
		arg.MonthID,
	)
	var i ExpectedPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Date,
		&i.MonthID,
	)
	return i, err
}

const deleteExpectedPayment = `-- name: DeleteExpectedPayment :exec
DELETE FROM expected_payments
WHERE id = $1
`

func (q *Queries) DeleteExpectedPayment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteExpectedPayment, id)
	return err
}

const editExpectedPayment = `-- name: EditExpectedPayment :one
UPDATE expected_payments
SET name = $2,
    amount = $3,
    date = $4
WHERE id = $1
RETURNING id, name, amount, date, month_id
`

type EditExpectedPaymentParams struct {
	ID     int64     `json:"id"`
	Name   string    `json:"name"`
	Amount int32     `json:"amount"`
	Date   time.Time `json:"date"`
}

func (q *Queries) EditExpectedPayment(ctx context.Context, arg EditExpectedPaymentParams) (ExpectedPayment, error) {
	row := q.db.QueryRow(ctx, editExpectedPayment,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Date,
	)
	var i ExpectedPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Date,
		&i.MonthID,
	)
	return i, err
}

const getExpectedPayment = `-- name: GetExpectedPayment :one
SELECT id, name, amount, date, month_id
FROM expected_payments
WHERE id = $1
LIMIT $1
`

func (q *Queries) GetExpectedPayment(ctx context.Context, limit int32) (ExpectedPayment, error) {
	row := q.db.QueryRow(ctx, getExpectedPayment, limit)
	var i ExpectedPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Date,
		&i.MonthID,
	)
	return i, err
}

const listExpectedPayments = `-- name: ListExpectedPayments :many
SELECT id, name, amount, date, month_id
FROM expected_payments
WHERE month_id = $1
ORDER BY date ASC
`

func (q *Queries) ListExpectedPayments(ctx context.Context, monthID int64) ([]ExpectedPayment, error) {
	rows, err := q.db.Query(ctx, listExpectedPayments, monthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpectedPayment{}
	for rows.Next() {
		var i ExpectedPayment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Date,
			&i.MonthID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
