// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type FixedEntry struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	DueDate    time.Time `json:"due_date"`
	PayDay     time.Time `json:"pay_day"`
	Amount     int32     `json:"amount"`
	Owner      string    `json:"owner"`
	OriginID   int64     `json:"origin_id"`
	CategoryID int64     `json:"category_id"`
}

type FixedEntryPaymentHistory struct {
	ID      int64     `json:"id"`
	EntryID int64     `json:"entry_id"`
	Amount  int32     `json:"amount"`
	Date    time.Time `json:"date"`
}

type Month struct {
	ID     int64     `json:"id"`
	UserID int64     `json:"user_id"`
	Date   time.Time `json:"date"`
}

type MonthEntry struct {
	ID      int64     `json:"id"`
	MonthID int64     `json:"month_id"`
	Name    string    `json:"name"`
	DueDate time.Time `json:"due_date"`
	// Date that is planned to pay this entry
	PayDate    time.Time `json:"pay_date"`
	Amount     int32     `json:"amount"`
	Owner      string    `json:"owner"`
	OriginID   int64     `json:"origin_id"`
	CategoryID int64     `json:"category_id"`
}

type Origin struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
}
