// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: monthly_expected_payments.sql

package db

import (
	"context"
)

const createMonthlyExpectedPayment = `-- name: CreateMonthlyExpectedPayment :one
INSERT INTO monthly_expected_payments (
  name,
  amount,
  day,
  user_id
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, name, amount, day, user_id
`

type CreateMonthlyExpectedPaymentParams struct {
	Name   string `json:"name"`
	Amount int32  `json:"amount"`
	Day    int16  `json:"day"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateMonthlyExpectedPayment(ctx context.Context, arg CreateMonthlyExpectedPaymentParams) (MonthlyExpectedPayment, error) {
	row := q.db.QueryRow(ctx, createMonthlyExpectedPayment,
		arg.Name,
		arg.Amount,
		arg.Day,
		arg.UserID,
	)
	var i MonthlyExpectedPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Day,
		&i.UserID,
	)
	return i, err
}

const deleteMonthlyExpectedPayment = `-- name: DeleteMonthlyExpectedPayment :exec
DELETE FROM monthly_expected_payments
WHERE id = $1
`

func (q *Queries) DeleteMonthlyExpectedPayment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMonthlyExpectedPayment, id)
	return err
}

const editMonthlyExpectedPayment = `-- name: EditMonthlyExpectedPayment :one
UPDATE monthly_expected_payments
SET name = $2,
    amount = $3,
    day = $4
WHERE id = $1
RETURNING id, name, amount, day, user_id
`

type EditMonthlyExpectedPaymentParams struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Amount int32  `json:"amount"`
	Day    int16  `json:"day"`
}

func (q *Queries) EditMonthlyExpectedPayment(ctx context.Context, arg EditMonthlyExpectedPaymentParams) (MonthlyExpectedPayment, error) {
	row := q.db.QueryRow(ctx, editMonthlyExpectedPayment,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Day,
	)
	var i MonthlyExpectedPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Day,
		&i.UserID,
	)
	return i, err
}

const getMonthlyExpectedPayment = `-- name: GetMonthlyExpectedPayment :one
SELECT id, name, amount, day, user_id
FROM monthly_expected_payments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMonthlyExpectedPayment(ctx context.Context, id int64) (MonthlyExpectedPayment, error) {
	row := q.db.QueryRow(ctx, getMonthlyExpectedPayment, id)
	var i MonthlyExpectedPayment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Day,
		&i.UserID,
	)
	return i, err
}

const listMonthlyExpectedPayments = `-- name: ListMonthlyExpectedPayments :many
SELECT id, name, amount, day, user_id
FROM monthly_expected_payments
WHERE user_id = $1
ORDER BY day ASC
`

func (q *Queries) ListMonthlyExpectedPayments(ctx context.Context, userID int64) ([]MonthlyExpectedPayment, error) {
	rows, err := q.db.Query(ctx, listMonthlyExpectedPayments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyExpectedPayment{}
	for rows.Next() {
		var i MonthlyExpectedPayment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Day,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
